---
title: "Statistical_Inference_Notes"
author: "Coursera Course by John Hopkins University"
date: "INSTRUCTORS: Dr. Brian Caffo, Dr. Roger D. Peng, Dr. Jeff Leek"
fontsize: 11pt
output: 
        pdf_document:
                toc: true
                toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Intro  
Instructor's Note:  
"*Statistical inference is the process of drawing conclusions about populations or scientific truths from data. There are many modes of performing inference including statistical modeling, data oriented strategies and explicit use of designs and randomization in analyses. Furthermore, there are broad theories (frequentists, Bayesian, likelihood, design based, …) & numerous complexities (missing data, observed and unobserved confounding, biases) for performing inference. A practitioner can often be left in a debilitating maze of techniques, philosophies and nuance. This course presents the fundamentals of inference in a practical approach for getting things done. After taking this course, students will understand the broad directions of statistical inference and use this information for making informed choices in analyzing data.*  
  
*All the best,*  
  
*Brian Caffo*"  

Statistical inference help us extend beyond a small subset of data to give answers about a population.  

Course Description:  
"*In this class students will learn the fundamentals of statistical inference. Students will receive a broad overview of the goals, assumptions and modes of performing statistical inference. Students will be able to perform inferential tasks in highly targeted settings and will be able to use the skills developed as a roadmap for more complex inferential challenges.*"  


## GitHub Link for Lectures  
**[Statistical Inference Lectures on GitHub](https://github.com/bcaffo/courses/tree/master/06_StatisticalInference)**  



## Course Book  
**[The book for this course is located on LeanPub](https://leanpub.com/LittleInferenceBook)**  


## Data Science Specialization Community Site  
**[The site is created using GitHub Pages](http://datasciencespecialization.github.io/)**  

## Homework Problems  
The homework problems are optional, they are a good opportunity to practice the skills covered in the course. There are also worked out solutions on youtube (linked to from the book)  

Here's all four homeworks as interactive web pages (it's probably better to just keep up with them from the book):  
* **[HW 1](http://bcaffo.github.io/courses/06_StatisticalInference/homework/hw1.html#1)**  
* **[HW 2](http://bcaffo.github.io/courses/06_StatisticalInference/homework/hw2.html#1)**  
* **[HW 3](http://bcaffo.github.io/courses/06_StatisticalInference/homework/hw3.html#1)**  
* **[HW 4](http://bcaffo.github.io/courses/06_StatisticalInference/homework/hw4.html#1)**  

**Reminder to commit (01), delete this line** ***AFTER*** **committing**  

# Probability & Expected Values  
## Probability mass functions  
## Probability densisty functions  
**Reminder to commit (02), delete this line** ***AFTER*** **committing**  

## Conditional Probability  
## Bayes' rule  
## Independence  
**Reminder to commit (03), delete this line** ***AFTER*** **committing**  

## Expected values  
## Expected values, simple examples  
## Expected values for PDFs  
**Reminder to commit (04), delete this line** ***AFTER*** **committing**  

## Lessons with `swirl()`  
## Quiz 1  
**Reminder to commit (S1), delete this line** ***AFTER*** **committing**  

# Variability, Distribution, & Asymptotics  
## Introduction to Variability  
## Variance Simulation Examples  
## Standard Error of the Mean  
## Variance Data Example  
**Reminder to commit (05), delete this line** ***AFTER*** **committing**  

## Binomial Distrubtion  
## Normal Distribution  
## Poisson  
**Reminder to commit (06), delete this line** ***AFTER*** **committing**  

## Asymptotics and the Law of Large Numbers (LLN)  
## Asymptotics and the Central Limit Theorem (CLT)  
## Asymptotics and Confidence Intervals  
**Reminder to commit (07), delete this line** ***AFTER*** **committing**  

## Lessons with `swirl()`  
## Quiz 2  
**Reminder to commit (S2), delete this line** ***AFTER*** **committing**  

# Intervals, Testing, & P-values  
## T Confidence Intervals  
## T Confidence Intervals Example  
## Independent Group T Intervals  
## A Note on Unequal Variance  
**Reminder to commit (08), delete this line** ***AFTER*** **committing**  

## Hypothesis Testing  
## Example of Choosing a Rejection Region  
## T Tests  
## Two Group Testing  
**Reminder to commit (09), delete this line** ***AFTER*** **committing**  

## P-Values  
## P-Value Further Examples  
**Reminder to commit (10), delete this line** ***AFTER*** **committing** 

## Lessons with `swirl()`  
## Quiz 3  
**Reminder to commit (S3), delete this line** ***AFTER*** **committing**  

# Power, Bootstrapping, & Permutation Tests  
## Power  
## Calculating Power  
## Notes on Power  
## T Test Power  
**Reminder to commit (11), delete this line** ***AFTER*** **committing**  

## Multiple Comparisons  
**Reminder to commit (12), delete this line** ***AFTER*** **committing**  

## Bootstrapping  
## Bootstrapping Example  
## Notes on the Bootstrap  
## Permutation Tests  
**Reminder to commit (13), delete this line** ***AFTER*** **committing**

## Lessons with `swirl()`  
## Quiz 4  

**Reminder to commit (S4), delete this line** ***BEFORE*** **committing**  













